dist: trusty
sudo: required

language: node_js
node_js: "node"

before_install:
 - npm install -g npm

install:
  - npm install

before_script:
  - npm install -g firebase-tools
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm test
  - ng build prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --project wfcchoops-f84d0

notifications:
  email:
    on_failure: change
    on_success: change
