sudo: required

language: node_js
node_js: "lts/*"

before_install:
 - npm install -g npm

install:
  - npm install

before_script:
  - npm install -g firebase-tools
  - export DISPLAY=:99.0

script:
  - npm test --watch=false
  - ng build --prod

notifications:
  email:
    on_failure: change
    on_success: change
